#!/bin/bash

# exit script if one command fails
set -o errexit

# exit script if Variable is not set
set -o nounset

INPUT=/bbx/mnt/input/biobox.yaml
OUTPUT=/bbx/mnt/output
METADATA=/bbx/mnt/metadata

# Since this script is the entrypoint to your container
# you can access the task in `docker run task` as the first argument
TASK=$1

# Ensure the biobox.yaml file is valid (TODO)
# validate-biobox-file --input ${INPUT} --schema /schema.yaml

# Use grep to get $TASK in /Taskfile
CMD=$(egrep ^${TASK}: /Taskfile | cut -f 2 -d ':')
if [[ -z ${CMD} ]]; then
  echo "Abort, no task found for '${TASK}'."
  exit 1
fi

# if /bbx/metadata is mounted create log.txt
if [ -d "$METADATA" ]; then
  CMD="($CMD) >& $METADATA/log.txt"
fi

TMP_DIR=$(mktemp -d)

INPUT_JSON="${TMP_DIR}/biobox.json"

$(yaml2json < ${INPUT} > $INPUT_JSON)

ARGUMENTS=$(jq --raw-output '.arguments' $INPUT_JSON )

#get assembly (fasta)
ASSEMBLY=$( echo $ARGUMENTS | jq --raw-output 'select(has("assemblies")) | .assemblies[].path' | tr '\n' ' ')

#get reads (gzipped? fastq)
READS=$( echo $ARGUMENTS | jq --raw-output 'select(has("reads")) | .reads.path')

# convert fastq zipped input to fasta (for building the index)
seqtk seq -a $READS > out.fasta

# Evaluation needs fastq reads
tar -xzf $READS
# strip gz (and possibly tar) from filename
READS=${READS%.gz}
# READS=${READS%.tar} single files, no tar
# append correct file ending
READS=$READS$".fq"

# get cache
CACHE=$( echo $ARGUMENTS | jq --raw-output 'select(has("cache")) | .cache ' )

# ALE requires an alignment instead of reads, convert using bowtie2, delete tmp files afterwards
bowtie2-build out.fasta tmp &> /dev/null #--quiet
bowtie2 -a -x tmp -q -U $READS --very-sensitive -a --reorder --un unaligned.reads -S sam_out.sam

# set usable file
SAM="../../sam_out.sam"

#check if cache is defined
if [ ! -z "$CACHE" ]; then
        TMP_DIR=$CACHE
fi

cd ALE/src/ #?
eval ${CMD}

cat << EOF > ${OUTPUT}/biobox.yaml
version: 0.1.0
results:
  - name: everything
    type: txt
    inline: false
    value: ALE_out.txt
    description: everything packed to .txt output
EOF 
